version: "3.9"

networks:
  # Create a new Docker network
  dev-network:
    driver: bridge

services:
  # Create service with PostgreSQL
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - dev-network

  # Create service
  weather_api:
    container_name: weather_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - dev-network
    depends_on:
      - db