DROP TABLE IF EXISTS Weathers CASCADE;

DROP TABLE IF EXISTS Cities CASCADE;

DROP TABLE IF EXISTS Lists CASCADE;

DROP TABLE IF EXISTS User_Lists CASCADE;

DROP TABLE IF EXISTS Users CASCADE;

DROP TABLE IF EXISTS List_Items CASCADE;
